/**
 * What the dataset cannot say about an airport, written by hand, by IATA code.
 *
 * `city` is the city an airport is known by, in place of the dataset's
 * municipality: the city's own name where the dataset gives the English one
 * («München», «Wien») — the English one staying where the language is not
 * written in the Latin alphabet («Tokyo», «Moscow») — the city served where
 * the dataset gives the suburb the runway is in, and the island where that is
 * what one flies to. `name` is what the airport is called day to day, in
 * place of the one worked out from its official name; it only ever shows
 * where the city has another airport.
 *
 * Never a parenthesis, a country or a whole label: what tells two entries
 * apart is worked out for every airport alike.
 */
export const NAMES = {
  // Argentina
  AEP: { name: 'Aeroparque' },
  EZE: { name: 'Ezeiza' },
  BRC: { city: 'Bariloche' },
  COR: { city: 'Córdoba' },
  CPC: { city: 'San Martín de los Andes' },
  IGR: { city: 'Puerto Iguazú' },
  JUJ: { city: 'Jujuy' },
  PRA: { city: 'Paraná' },
  RGA: { city: 'Río Grande' },
  RGL: { city: 'Río Gallegos' },
  TUC: { city: 'Tucumán' },
  REL: { city: 'Trelew' },

  // The rest of the Americas
  ANU: { city: 'Antigua' },
  AUA: { city: 'Aruba' },
  BGI: { city: 'Barbados' },
  BDA: { city: 'Bermuda' },
  BON: { city: 'Bonaire' },
  CUR: { city: 'Curaçao' },
  GCM: { city: 'Grand Cayman' },
  EIS: { city: 'Tortola' },
  TAB: { city: 'Tobago' },
  UYU: { city: 'Uyuni' },
  VVI: { city: 'Santa Cruz de la Sierra', name: 'Viru Viru' },
  SRZ: { city: 'Santa Cruz de la Sierra', name: 'El Trompillo' },
  GIG: { city: 'Rio de Janeiro', name: 'Galeão' },
  SDU: { name: 'Santos Dumont' },
  GRU: { name: 'Guarulhos' },
  CGH: { name: 'Congonhas' },
  YQB: { city: 'Québec' },
  YUL: { name: 'Trudeau' },
  YMX: { name: 'Mirabel' },
  YHU: { name: 'Saint-Hubert' },
  YTZ: { name: 'Billy Bishop' },
  CCP: { city: 'Concepción' },
  IPC: { city: 'Isla de Pascua' },
  LSC: { city: 'La Serena' },
  CPO: { city: 'Copiapó' },
  CXJ: { city: 'Caxias do Sul' },
  CZS: { city: 'Cruzeiro do Sul' },
  JJD: { city: 'Jericoacoara' },
  CKS: { city: 'Carajás' },
  APO: { city: 'Apartadó' },
  PJM: { city: 'Puerto Jiménez' },
  NOB: { city: 'Nosara' },
  JBQ: { city: 'Santo Domingo', name: 'La Isabela' },
  FRS: { city: 'Flores' },
  MTT: { city: 'Minatitlán' },
  TAM: { city: 'Tampico' },
  PAC: { city: 'Ciudad de Panamá', name: 'Albrook' },
  MAZ: { city: 'Mayagüez' },
  SVZ: { city: 'San Antonio del Táchira' },
  BOG: { city: 'Bogotá' },
  MDE: { name: 'José María Córdova' },
  EOH: { name: 'Olaya Herrera' },
  CMW: { city: 'Camagüey' },
  HAV: { city: 'La Habana' },
  HOG: { city: 'Holguín' },
  SCU: { city: 'Santiago de Cuba' },
  VRA: { city: 'Varadero' },
  STI: { city: 'Santiago de los Caballeros' },
  ESM: { city: 'Esmeraldas' },
  GPS: { city: 'Galápagos' },
  CAY: { city: 'Cayenne' },
  GUA: { city: 'Ciudad de Guatemala' },
  RTB: { city: 'Roatán' },
  XPL: { city: 'Tegucigalpa', name: 'Palmerola' },
  TGU: { name: 'Toncontín' },
  CAP: { city: 'Cap-Haïtien' },
  BJX: { city: 'León' },
  MEX: { city: 'Ciudad de México', name: 'Benito Juárez' },
  NLU: { city: 'Ciudad de México', name: 'Felipe Ángeles' },
  MZT: { city: 'Mazatlán' },
  SJD: { city: 'Los Cabos' },
  ZIH: { city: 'Ixtapa-Zihuatanejo' },
  PTY: { city: 'Ciudad de Panamá', name: 'Tocumen' },
  MVD: { city: 'Montevideo' },
  CCS: { city: 'Caracas' },
  PZO: { city: 'Puerto Ordaz' },
  DFW: { city: 'Dallas', name: 'DFW' },
  DAL: { name: 'Love Field' },
  EWR: { city: 'New York', name: 'Newark' },
  JFK: { name: 'JFK' },
  LGA: { name: 'LaGuardia' },
  IAD: { city: 'Washington', name: 'Dulles' },
  DCA: { name: 'Reagan' },
  HOU: { name: 'Hobby' },
  IAH: { name: 'Intercontinental' },
  MDW: { name: 'Midway' },
  ORD: { name: "O'Hare" },
  BFI: { name: 'Boeing Field' },
  RFD: { city: 'Rockford' },
  KOA: { city: 'Kona' },
  OGG: { city: 'Maui' },
  PIE: { city: 'St. Petersburg' },
  RDU: { city: 'Raleigh-Durham' },
  SJC: { city: 'San José' },
  STL: { city: 'St. Louis' },

  // Europe
  TIA: { city: 'Tirana' },
  GRZ: { city: 'Graz' },
  KLU: { city: 'Klagenfurt' },
  VIE: { city: 'Wien' },
  BNX: { city: 'Banja Luka' },
  TZL: { city: 'Tuzla' },
  BRU: { city: 'Bruxelles' },
  GVA: { city: 'Genève' },
  ZRH: { city: 'Zürich' },
  ECN: { city: 'Nicosia' },
  OSR: { city: 'Ostrava' },
  PRG: { city: 'Praha' },
  FRA: { city: 'Frankfurt' },
  HHN: { city: 'Hahn' },
  FKB: { city: 'Karlsruhe' },
  FMO: { city: 'Münster' },
  KSF: { city: 'Kassel' },
  LEJ: { city: 'Leipzig' },
  MUC: { city: 'München' },
  NUE: { city: 'Nürnberg' },
  PAD: { city: 'Paderborn' },
  CPH: { city: 'København' },
  ACE: { city: 'Lanzarote' },
  FUE: { city: 'Fuerteventura' },
  LPA: { city: 'Gran Canaria' },
  MAH: { city: 'Menorca' },
  OVD: { city: 'Asturias' },
  RMU: { city: 'Murcia' },
  SVQ: { city: 'Sevilla' },
  LCG: { city: 'A Coruña' },
  LEN: { city: 'León' },
  EAS: { city: 'San Sebastián' },
  SPC: { city: 'La Palma' },
  VDE: { city: 'El Hierro' },
  VIT: { city: 'Vitoria' },
  LEU: { city: "La Seu d'Urgell" },
  PXO: { city: 'Porto Santo' },
  PIX: { city: 'Pico' },
  SJZ: { city: 'São Jorge' },
  FLW: { city: 'Flores' },
  GRW: { city: 'Graciosa' },
  TFN: { name: 'Norte' },
  TFS: { name: 'Sur' },
  BSL: { city: 'Basel' },
  LIL: { city: 'Lille' },
  LYS: { city: 'Lyon' },
  MRS: { city: 'Marseille' },
  CDG: { name: 'Charles de Gaulle' },
  ORY: { name: 'Orly' },
  EDI: { city: 'Edinburgh' },
  EMA: { city: 'East Midlands' },
  BHD: { name: 'City' },
  LHR: { name: 'Heathrow' },
  LGW: { name: 'Gatwick' },
  STN: { name: 'Stansted' },
  LTN: { city: 'London', name: 'Luton' },
  LCY: { name: 'City' },
  KUT: { city: 'Kutaisi' },
  ATH: { city: 'Athens' },
  CFU: { city: 'Corfu' },
  CHQ: { city: 'Chania' },
  JTR: { city: 'Santorini' },
  KGS: { city: 'Kos' },
  ZAG: { city: 'Zagreb' },
  NOC: { city: 'Knock' },
  IOM: { city: 'Isle of Man' },
  BGY: { city: 'Bergamo' },
  LIN: { city: 'Milano', name: 'Linate' },
  MXP: { city: 'Milano', name: 'Malpensa' },
  CIA: { city: 'Roma', name: 'Ciampino' },
  FCO: { city: 'Roma', name: 'Fiumicino' },
  TRN: { city: 'Torino' },
  TRS: { city: 'Trieste' },
  VRN: { city: 'Verona' },
  SKP: { city: 'Skopje' },
  MLA: { city: 'Malta' },
  EVE: { city: 'Harstad-Narvik' },
  KRK: { city: 'Kraków' },
  RZE: { city: 'Rzeszów' },
  WAW: { city: 'Warszawa', name: 'Chopin' },
  WMI: { city: 'Warszawa', name: 'Modlin' },
  FNC: { city: 'Madeira' },
  LIS: { city: 'Lisboa' },
  OTP: { city: 'București', name: 'Henri Coandă' },
  BBU: { city: 'București', name: 'Băneasa' },
  BEG: { city: 'Beograd' },
  IAR: { city: 'Yaroslavl' },
  LED: { city: 'St. Petersburg' },
  VVO: { city: 'Vladivostok' },
  VST: { city: 'Västerås' },
  SCR: { city: 'Sälen' },
  LJU: { city: 'Ljubljana' },
  ADB: { city: 'İzmir' },
  COV: { city: 'Adana', name: 'Çukurova' },
  IST: { city: 'İstanbul' },
  SAW: { city: 'İstanbul', name: 'Sabiha Gökçen' },

  // Africa and the Middle East
  HEA: { city: 'Herat' },
  LAD: { name: 'Quatro de Fevereiro' },
  NBJ: { name: 'Agostinho Neto' },
  BVC: { city: 'Boa Vista' },
  SID: { city: 'Sal' },
  VXE: { city: 'São Vicente' },
  JIB: { city: 'Djibouti' },
  ALG: { city: 'Alger' },
  GJL: { city: 'Jijel' },
  ORN: { city: 'Oran' },
  TLM: { city: 'Tlemcen' },
  HMB: { city: 'Sohag' },
  SPX: { city: 'Giza' },
  EBL: { city: 'Erbil' },
  ADJ: { name: 'Marka' },
  AMM: { name: 'Queen Alia' },
  BEN: { city: 'Benghazi' },
  LAQ: { city: 'Al Bayda' },
  BEM: { city: 'Béni Mellal' },
  FEZ: { city: 'Fès' },
  NDR: { city: 'Nador' },
  OUD: { city: 'Oujda' },
  RAK: { city: 'Marrakech' },
  TNG: { city: 'Tanger' },
  TOM: { city: 'Tombouctou' },
  MRU: { city: 'Mauritius' },
  LLW: { city: 'Lilongwe' },
  ENU: { city: 'Enugu' },
  RUN: { city: 'Saint-Denis' },
  DMM: { city: 'Dammam' },
  NUM: { city: 'Neom' },
  SEZ: { city: 'Mahé' },
  SHO: { city: 'Manzini' },
  DJE: { city: 'Djerba' },
  JRO: { city: 'Kilimanjaro' },

  // Asia and the Pacific
  MEL: { name: 'Tullamarine' },
  MCY: { city: 'Sunshine Coast' },
  NTL: { city: 'Newcastle' },
  LXA: { city: 'Lhasa' },
  XNN: { city: 'Xining' },
  PEK: { name: 'Capital' },
  PKX: { name: 'Daxing' },
  PVG: { name: 'Pudong' },
  SHA: { name: 'Hongqiao' },
  SUV: { city: 'Suva' },
  KSA: { city: 'Kosrae' },
  TKK: { city: 'Chuuk' },
  YAP: { city: 'Yap' },
  GUM: { city: 'Guam' },
  BDJ: { city: 'Banjarmasin' },
  DJJ: { city: 'Jayapura' },
  DPS: { city: 'Bali' },
  KNO: { city: 'Medan' },
  LOP: { city: 'Lombok' },
  DXN: { city: 'Noida' },
  GOI: { city: 'Goa', name: 'Dabolim' },
  GOX: { city: 'Goa', name: 'Mopa' },
  SAG: { city: 'Shirdi' },
  NRT: { city: 'Tokyo', name: 'Narita' },
  HND: { name: 'Haneda' },
  ITM: { name: 'Itami' },
  KIX: { name: 'Kansai' },
  NGO: { city: 'Nagoya', name: 'Centrair' },
  NKM: { name: 'Komaki' },
  OKA: { city: 'Okinawa' },
  SDJ: { city: 'Sendai' },
  KCZ: { city: 'Kochi' },
  FSZ: { city: 'Shizuoka' },
  IBR: { city: 'Ibaraki' },
  KMQ: { city: 'Komatsu' },
  IKU: { city: 'Issyk-Kul' },
  KTI: { name: 'Techo' },
  KOS: { city: 'Sihanoukville' },
  DSY: { city: 'Dara Sakor' },
  ICN: { name: 'Incheon' },
  GMP: { name: 'Gimpo' },
  CJU: { city: 'Jeju' },
  YNY: { city: 'Yangyang' },
  HSA: { city: 'Turkistan' },
  MAJ: { city: 'Majuro' },
  MFM: { city: 'Macau' },
  HAQ: { city: 'Hanimaadhoo' },
  KUL: { city: 'Kuala Lumpur' },
  SZB: { city: 'Kuala Lumpur', name: 'Subang' },
  BWA: { city: 'Bhairahawa' },
  BCD: { city: 'Bacolod' },
  CEB: { city: 'Cebu' },
  CGY: { city: 'Cagayan de Oro' },
  CRK: { city: 'Clark' },
  ILO: { city: 'Iloilo' },
  LAO: { city: 'Laoag' },
  SFS: { city: 'Subic Bay' },
  TAG: { city: 'Bohol' },
  GWD: { city: 'Gwadar' },
  ISB: { city: 'Islamabad' },
  ROR: { city: 'Koror' },
  BKK: { name: 'Suvarnabhumi' },
  DMK: { name: 'Don Mueang' },
  USM: { city: 'Koh Samui' },
  UTP: { city: 'Pattaya' },
  VAV: { city: "Vava'u" },
  TPE: { city: 'Taipei', name: 'Taoyuan' },
  TSA: { name: 'Songshan' },
  HUN: { city: 'Hualien' },
  MZG: { city: 'Penghu' },
  CXR: { city: 'Nha Trang' },
  HUI: { city: 'Hue' },
  PQC: { city: 'Phu Quoc' },
  WLS: { city: 'Wallis' },

  // The Americas, the smaller airports
  AXA: { city: 'Anguilla' },
  SBH: { city: 'Saint-Barthélemy' },
  EUX: { city: 'Sint Eustatius' },
  SAB: { city: 'Saba' },
  SJK: { city: 'São José dos Campos' },
  GGT: { city: 'George Town' },
  TZN: { city: 'Congo Town' },
  SAQ: { city: 'San Andros' },
  YKF: { city: 'Kitchener-Waterloo' },
  YQA: { city: 'Muskoka' },
  ZBF: { city: 'Bathurst' },
  YCM: { city: 'St. Catharines' },
  YAM: { city: 'Sault Ste. Marie' },
  YXJ: { city: 'Fort St. John' },
  YGR: { city: 'Îles-de-la-Madeleine' },
  PSO: { city: 'Pasto' },
  SJE: { city: 'San José del Guaviare' },
  SVI: { city: 'San Vicente del Caguán' },
  DOM: { city: 'Dominica', name: 'Douglas-Charles' },
  DCF: { city: 'Dominica', name: 'Canefield' },
  GND: { city: 'Grenada' },
  OGL: { city: 'Georgetown', name: 'Ogle' },
  JEE: { city: 'Jérémie' },
  OCJ: { city: 'Ocho Rios' },
  KTP: { city: 'Kingston', name: 'Tinson Pen' },
  SKB: { city: 'Saint Kitts' },
  NEV: { city: 'Nevis' },
  CYB: { city: 'Cayman Brac' },
  UVF: { city: 'Saint Lucia', name: 'Hewanorra' },
  SLU: { city: 'Saint Lucia', name: 'George F. L. Charles' },
  BOC: { city: 'Bocas del Toro' },
  SIG: { name: 'Isla Grande' },
  GDT: { city: 'Grand Turk' },
  VPS: { city: 'Fort Walton Beach' },
  HDN: { city: 'Steamboat Springs' },
  EGE: { city: 'Vail' },
  SUN: { city: 'Sun Valley' },
  GCN: { city: 'Grand Canyon' },
  GRK: { city: 'Killeen' },
  LAF: { city: 'Lafayette' },
  MBS: { city: 'Saginaw' },
  CMI: { city: 'Champaign' },
  CWA: { city: 'Wausau' },
  TRI: { city: 'Tri-Cities' },
  TTN: { city: 'Trenton' },
  CIU: { city: 'Sault Ste. Marie' },
  CKB: { city: 'Clarksburg' },
  CMX: { city: 'Houghton' },
  MQT: { city: 'Marquette' },
  IMT: { city: 'Iron Mountain' },
  BKW: { city: 'Beckley' },
  OAJ: { city: 'Jacksonville' },
  PIB: { city: 'Hattiesburg' },
  SHD: { city: 'Staunton' },
  JHM: { city: 'Maui', name: 'Kapalua' },
  HNM: { city: 'Maui', name: 'Hana' },
  MKK: { city: 'Molokai' },
  LNY: { city: 'Lanai' },
  MQS: { city: 'Mustique' },
  PMV: { city: 'Isla de Margarita' },
  LSP: { city: 'Punto Fijo' },
  VIJ: { city: 'Virgin Gorda' },
  STT: { city: 'St. Thomas' },
  STX: { city: 'St. Croix' },

  // Europe, the smaller airports
  LGG: { city: 'Liège' },
  ANR: { city: 'Antwerpen' },
  LUG: { city: 'Lugano' },
  RLG: { city: 'Rostock' },
  FCN: { city: 'Cuxhaven' },
  HDF: { city: 'Heringsdorf' },
  JYV: { city: 'Jyväskylä' },
  ENF: { city: 'Enontekiö' },
  RNS: { city: 'Rennes' },
  TLN: { city: 'Toulon' },
  ETZ: { city: 'Metz-Nancy' },
  XCR: { city: 'Châlons-en-Champagne' },
  HUY: { city: 'Humberside' },
  MME: { city: 'Teesside' },
  LSI: { city: 'Shetland', name: 'Sumburgh' },
  BEB: { city: 'Benbecula' },
  BRR: { city: 'Barra' },
  TRE: { city: 'Tiree' },
  ILY: { city: 'Islay' },
  SEN: { city: 'London', name: 'Southend' },
  GCI: { city: 'Guernsey' },
  ACI: { city: 'Alderney' },
  JER: { city: 'Jersey' },
  EFL: { city: 'Kefalonia' },
  JSH: { city: 'Sitia' },
  VOL: { city: 'Volos' },
  JKH: { city: 'Chios' },
  SMI: { city: 'Samos' },
  AOK: { city: 'Karpathos' },
  BWK: { city: 'Brač' },
  SOB: { city: 'Hévíz' },
  KIR: { city: 'Kerry' },
  AOI: { city: 'Ancona' },
  VBS: { city: 'Brescia' },
  CUF: { city: 'Cuneo' },
  CRV: { city: 'Crotone' },
  EBA: { city: 'Elba' },
  RIX: { city: 'Rīga' },
  RMO: { city: 'Chișinău' },
  IAS: { city: 'Iași' },
  HAU: { city: 'Haugesund' },
  MOL: { city: 'Molde' },
  KSU: { city: 'Kristiansund' },
  BDU: { city: 'Bardufoss' },
  BNN: { city: 'Brønnøysund' },
  SSJ: { city: 'Sandnessjøen' },
  SKN: { city: 'Stokmarknes' },
  SRP: { city: 'Stord' },
  IEG: { city: 'Zielona Góra' },
  SZY: { city: 'Olsztyn' },
  TER: { city: 'Terceira' },
  SMA: { city: 'Santa Maria' },
  BAY: { city: 'Baia Mare' },
  TGM: { city: 'Târgu Mureș' },
  NLI: { city: 'Nikolayevsk-on-Amur' },
  OGZ: { city: 'Vladikavkaz' },
  ARH: { city: 'Arkhangelsk' },
  BQS: { city: 'Blagoveshchensk' },
  MRV: { city: 'Mineralnye Vody' },
  ULY: { city: 'Ulyanovsk', name: 'Vostochny' },
  ULV: { name: 'Baratayevka' },
  IGT: { city: 'Magas' },
  PYJ: { city: 'Udachny' },
  PWE: { city: 'Pevek' },
  BLE: { city: 'Borlänge' },
  KRF: { city: 'Kramfors' },
  YEI: { city: 'Bursa' },
  KZR: { city: 'Kütahya' },
  GZP: { city: 'Alanya' },

  // Africa and the Middle East, the smaller airports
  PNR: { city: 'Pointe-Noire' },
  MMO: { city: 'Maio' },
  SNE: { city: 'São Nicolau' },
  TEE: { city: 'Tébessa' },
  GHA: { city: 'Ghardaïa' },
  ELU: { city: 'El Oued' },
  GDQ: { city: 'Gondar' },
  POG: { city: 'Port-Gentil' },
  ZBR: { city: 'Chabahar' },
  PGU: { city: 'Asaluyeh' },
  MRE: { city: 'Masai Mara', name: 'Serena' },
  ASV: { city: 'Amboseli' },
  NYK: { city: 'Nanyuki' },
  DIE: { city: 'Antsiranana' },
  SMS: { city: 'Sainte-Marie' },
  MZI: { city: 'Mopti' },
  RRG: { city: 'Rodrigues' },
  MPA: { city: 'Katima Mulilo' },
  LUD: { city: 'Lüderitz' },
  BNI: { city: 'Benin City' },
  QRW: { city: 'Warri' },
  RSI: { city: 'Red Sea' },
  PRI: { city: 'Praslin' },
  PCP: { city: 'Príncipe' },
  SCT: { city: 'Socotra' },
  MBD: { city: 'Mahikeng' },

  // Asia and the Pacific, the smaller airports
  AVV: { city: 'Melbourne', name: 'Avalon' },
  MEB: { city: 'Melbourne', name: 'Essendon' },
  KGI: { city: 'Kalgoorlie' },
  GET: { city: 'Geraldton' },
  WGA: { city: 'Wagga Wagga' },
  ABX: { city: 'Albury' },
  AYQ: { city: 'Uluru' },
  HID: { city: 'Horn Island' },
  OKY: { city: 'Oakey' },
  RAR: { city: 'Rarotonga' },
  JZH: { city: 'Jiuzhaigou' },
  DIG: { city: 'Shangri-La' },
  TCZ: { city: 'Tengchong' },
  XIC: { city: 'Xichang' },
  YIN: { city: 'Yining' },
  LUM: { city: 'Mangshi' },
  KGT: { city: 'Kangding' },
  DCY: { city: 'Daocheng' },
  RKZ: { city: 'Shigatse' },
  DDR: { city: 'Tingri' },
  BPX: { city: 'Qamdo' },
  LZG: { city: 'Langzhong' },
  JMJ: { city: 'Lancang' },
  CWJ: { city: 'Cangyuan' },
  DTU: { city: 'Wudalianchi' },
  CHG: { city: 'Chaoyang' },
  FUG: { city: 'Fuyang' },
  JNH: { city: 'Jiaxing' },
  WUZ: { city: 'Wuzhou' },
  YSQ: { city: 'Songyuan' },
  PNI: { city: 'Pohnpei' },
  TNJ: { city: 'Tanjung Pinang' },
  BEJ: { city: 'Tanjung Redeb' },
  NTX: { city: 'Natuna' },
  WNI: { city: 'Wakatobi' },
  NPO: { city: 'Nanga Pinoh' },
  PSU: { city: 'Putussibau' },
  PDO: { city: 'Pendopo' },
  HLP: { name: 'Halim' },
  DHM: { city: 'Dharamshala' },
  IXB: { city: 'Bagdogra' },
  KUU: { city: 'Kullu' },
  AYJ: { city: 'Ayodhya' },
  IXD: { city: 'Prayagraj' },
  RJA: { city: 'Rajahmundry' },
  KJB: { city: 'Kurnool' },
  SDW: { city: 'Sindhudurg' },
  HGI: { city: 'Itanagar' },
  CCJ: { city: 'Kozhikode' },
  AKJ: { city: 'Asahikawa' },
  FKS: { city: 'Fukushima' },
  GAJ: { city: 'Yamagata' },
  MMB: { city: 'Memanbetsu' },
  ONJ: { city: 'Odate-Noshiro' },
  TKN: { city: 'Tokunoshima' },
  OKE: { city: 'Okinoerabu' },
  KTD: { city: 'Kitadaito' },
  LPQ: { city: 'Luang Prabang' },
  MGZ: { city: 'Myeik' },
  SPN: { city: 'Saipan' },
  ROP: { city: 'Rota' },
  TIQ: { city: 'Tinian' },
  AOR: { city: 'Alor Setar' },
  KBR: { city: 'Kota Bharu' },
  MKZ: { city: 'Melaka' },
  TOD: { city: 'Tioman' },
  NLK: { city: 'Norfolk Island' },
  KAT: { city: 'Kaitaia' },
  CHT: { city: 'Chatham Islands' },
  BOB: { city: 'Bora Bora' },
  MOZ: { city: 'Moorea' },
  HUH: { city: 'Huahine' },
  RFP: { city: 'Raiatea' },
  TIH: { city: 'Tikehau' },
  AUQ: { city: 'Hiva Oa' },
  RAB: { city: 'Rabaul' },
  GUR: { city: 'Alotau' },
  GKA: { city: 'Goroka' },
  CBO: { city: 'Cotabato' },
  TAC: { city: 'Tacloban' },
  DGT: { city: 'Dumaguete' },
  TUG: { city: 'Tuguegarao' },
  SUG: { city: 'Surigao' },
  RXS: { city: 'Roxas' },
  CYP: { city: 'Calbayog' },
  CYZ: { city: 'Cauayan' },
  PZH: { city: 'Zhob' },
  WNS: { city: 'Nawabshah' },
  XSP: { city: 'Singapore', name: 'Seletar' },
  TDX: { city: 'Trat' },
  KRW: { city: 'Türkmenbaşy' },
  CYI: { city: 'Chiayi' },
  KNH: { city: 'Kinmen' },
  TTT: { city: 'Taitung' },
  UIH: { city: 'Quy Nhon' },
  CAH: { city: 'Ca Mau' },
};

/**
 * What a region is called in the app's language, by its ISO code, where that
 * is not what the dataset calls it. A region only ever shows where one
 * country has two places of one name, and a country beside it is in Spanish.
 */
export const REGION_NAMES = {
  'US-HI': 'Hawái',
  'US-LA': 'Luisiana',
  'US-MI': 'Míchigan',
  'US-MS': 'Misisipi',
  'US-MO': 'Misuri',
  'US-NH': 'Nuevo Hampshire',
  'US-NJ': 'Nueva Jersey',
  'US-NM': 'Nuevo México',
  'US-NY': 'Nueva York',
  'US-NC': 'Carolina del Norte',
  'US-ND': 'Dakota del Norte',
  'US-OR': 'Oregón',
  'US-PA': 'Pensilvania',
  'US-SC': 'Carolina del Sur',
  'US-SD': 'Dakota del Sur',
  'US-WV': 'Virginia Occidental',
  'US-DC': 'Washington D. C.',
  'CA-BC': 'Columbia Británica',
  'CA-NB': 'Nuevo Brunswick',
  'CA-NL': 'Terranova y Labrador',
  'CA-NS': 'Nueva Escocia',
  'CA-NT': 'Territorios del Noroeste',
  'CA-PE': 'Isla del Príncipe Eduardo',
  'CA-YT': 'Yukón',
  'AU-NSW': 'Nueva Gales del Sur',
  'AU-NT': 'Territorio del Norte',
  'AU-SA': 'Australia Meridional',
  'AU-WA': 'Australia Occidental',
  'AU-ACT': 'Territorio de la Capital Australiana',
  'GB-ENG': 'Inglaterra',
  'GB-SCT': 'Escocia',
  'GB-WLS': 'Gales',
  'GB-NIR': 'Irlanda del Norte',
  'CN-15': 'Mongolia Interior',
  'CN-54': 'Tíbet',
};
