import type { TripItem } from '../../lib/offline/specs';
import { normalize } from '../../utils/textUtils';

/**
 * The airports a pasaje offers, by IATA code. Curated on purpose: the full IATA
 * set is some nine thousand entries, and everything bundled is precached on
 * every device whether it is ever used or not. This is a few KB of the airports
 * a household actually flies through, and anything missing is still accepted —
 * three letters are all a code ever is.
 */
export const AIRPORTS: readonly (readonly [string, string])[] = [
  // Argentina
  ['AEP', 'Buenos Aires (Aeroparque)'],
  ['EZE', 'Buenos Aires (Ezeiza)'],
  ['COR', 'Córdoba'],
  ['ROS', 'Rosario'],
  ['MDZ', 'Mendoza'],
  ['BRC', 'Bariloche'],
  ['FTE', 'El Calafate'],
  ['USH', 'Ushuaia'],
  ['IGR', 'Puerto Iguazú'],
  ['SLA', 'Salta'],
  ['JUJ', 'Jujuy'],
  ['TUC', 'Tucumán'],
  ['NQN', 'Neuquén'],
  ['BHI', 'Bahía Blanca'],
  ['MDQ', 'Mar del Plata'],
  ['CRD', 'Comodoro Rivadavia'],
  ['RGL', 'Río Gallegos'],
  ['RGA', 'Río Grande'],
  ['PMY', 'Puerto Madryn'],
  ['VDM', 'Viedma'],
  ['EQS', 'Esquel'],
  ['CPC', 'San Martín de los Andes'],
  ['AFA', 'San Rafael'],
  ['UAQ', 'San Juan'],
  ['LUQ', 'San Luis'],
  ['CTC', 'Catamarca'],
  ['SDE', 'Santiago del Estero'],
  ['RES', 'Resistencia'],
  ['CNQ', 'Corrientes'],
  ['PSS', 'Posadas'],
  ['FMA', 'Formosa'],
  ['SFN', 'Santa Fe'],
  ['PRA', 'Paraná'],
  // Uruguay, Paraguay, Bolivia, Chile
  ['MVD', 'Montevideo'],
  ['PDP', 'Punta del Este'],
  ['ASU', 'Asunción'],
  ['VVI', 'Santa Cruz de la Sierra'],
  ['LPB', 'La Paz'],
  ['CBB', 'Cochabamba'],
  ['SCL', 'Santiago de Chile'],
  ['IPC', 'Isla de Pascua'],
  ['PMC', 'Puerto Montt'],
  ['PUQ', 'Punta Arenas'],
  ['BBA', 'Balmaceda'],
  ['ZCO', 'Temuco'],
  ['LSC', 'La Serena'],
  ['ANF', 'Antofagasta'],
  ['CJC', 'Calama'],
  ['IQQ', 'Iquique'],
  ['ARI', 'Arica'],
  // Brasil
  ['GRU', 'São Paulo (Guarulhos)'],
  ['CGH', 'São Paulo (Congonhas)'],
  ['GIG', 'Río de Janeiro (Galeão)'],
  ['SDU', 'Río de Janeiro (Santos Dumont)'],
  ['BSB', 'Brasilia'],
  ['CNF', 'Belo Horizonte'],
  ['SSA', 'Salvador'],
  ['REC', 'Recife'],
  ['FOR', 'Fortaleza'],
  ['NAT', 'Natal'],
  ['MCZ', 'Maceió'],
  ['JPA', 'João Pessoa'],
  ['POA', 'Porto Alegre'],
  ['CWB', 'Curitiba'],
  ['FLN', 'Florianópolis'],
  ['IGU', 'Foz do Iguaçu'],
  ['VIX', 'Vitória'],
  ['CGB', 'Cuiabá'],
  ['MAO', 'Manaos'],
  ['BEL', 'Belém'],
  // Resto de América del Sur
  ['LIM', 'Lima'],
  ['CUZ', 'Cusco'],
  ['AQP', 'Arequipa'],
  ['IQT', 'Iquitos'],
  ['TRU', 'Trujillo'],
  ['PIU', 'Piura'],
  ['UIO', 'Quito'],
  ['GYE', 'Guayaquil'],
  ['GPS', 'Galápagos'],
  ['BOG', 'Bogotá'],
  ['MDE', 'Medellín'],
  ['CTG', 'Cartagena'],
  ['CLO', 'Cali'],
  ['SMR', 'Santa Marta'],
  ['BAQ', 'Barranquilla'],
  ['ADZ', 'San Andrés'],
  ['CCS', 'Caracas'],
  // Centroamérica y el Caribe
  ['PTY', 'Ciudad de Panamá'],
  ['SJO', 'San José de Costa Rica'],
  ['LIR', 'Liberia (Guanacaste)'],
  ['GUA', 'Ciudad de Guatemala'],
  ['SAL', 'San Salvador'],
  ['TGU', 'Tegucigalpa'],
  ['SAP', 'San Pedro Sula'],
  ['MGA', 'Managua'],
  ['BZE', 'Belice'],
  ['HAV', 'La Habana'],
  ['VRA', 'Varadero'],
  ['PUJ', 'Punta Cana'],
  ['SDQ', 'Santo Domingo'],
  ['SJU', 'San Juan de Puerto Rico'],
  ['MBJ', 'Montego Bay'],
  ['KIN', 'Kingston'],
  ['NAS', 'Nassau'],
  ['GCM', 'Gran Caimán'],
  ['PLS', 'Providenciales'],
  ['AUA', 'Aruba'],
  ['CUR', 'Curazao'],
  ['SXM', 'San Martín'],
  ['ANU', 'Antigua'],
  ['BGI', 'Barbados'],
  ['POS', 'Puerto España'],
  // México
  ['MEX', 'Ciudad de México'],
  ['CUN', 'Cancún'],
  ['GDL', 'Guadalajara'],
  ['MTY', 'Monterrey'],
  ['SJD', 'Los Cabos'],
  ['PVR', 'Puerto Vallarta'],
  ['MID', 'Mérida'],
  ['OAX', 'Oaxaca'],
  ['TIJ', 'Tijuana'],
  // Estados Unidos
  ['JFK', 'Nueva York (JFK)'],
  ['EWR', 'Nueva York (Newark)'],
  ['LGA', 'Nueva York (LaGuardia)'],
  ['BOS', 'Boston'],
  ['PHL', 'Filadelfia'],
  ['IAD', 'Washington (Dulles)'],
  ['DCA', 'Washington (Reagan)'],
  ['BWI', 'Baltimore'],
  ['MIA', 'Miami'],
  ['FLL', 'Fort Lauderdale'],
  ['PBI', 'West Palm Beach'],
  ['MCO', 'Orlando'],
  ['TPA', 'Tampa'],
  ['RSW', 'Fort Myers'],
  ['JAX', 'Jacksonville'],
  ['ATL', 'Atlanta'],
  ['CLT', 'Charlotte'],
  ['RDU', 'Raleigh-Durham'],
  ['CHS', 'Charleston'],
  ['SAV', 'Savannah'],
  ['BNA', 'Nashville'],
  ['MEM', 'Memphis'],
  ['MSY', 'Nueva Orleans'],
  ['ORD', 'Chicago (O’Hare)'],
  ['MDW', 'Chicago (Midway)'],
  ['DTW', 'Detroit'],
  ['MSP', 'Mineápolis'],
  ['STL', 'San Luis (Misuri)'],
  ['MCI', 'Kansas City'],
  ['OMA', 'Omaha'],
  ['IND', 'Indianápolis'],
  ['CVG', 'Cincinnati'],
  ['CLE', 'Cleveland'],
  ['PIT', 'Pittsburgh'],
  ['BUF', 'Búfalo'],
  ['PVD', 'Providence'],
  ['BDL', 'Hartford'],
  ['DFW', 'Dallas'],
  ['IAH', 'Houston'],
  ['AUS', 'Austin'],
  ['SAT', 'San Antonio'],
  ['ELP', 'El Paso'],
  ['DEN', 'Denver'],
  ['SLC', 'Salt Lake City'],
  ['ABQ', 'Albuquerque'],
  ['PHX', 'Phoenix'],
  ['TUS', 'Tucson'],
  ['LAS', 'Las Vegas'],
  ['LAX', 'Los Ángeles'],
  ['SAN', 'San Diego'],
  ['SFO', 'San Francisco'],
  ['SJC', 'San José (California)'],
  ['OAK', 'Oakland'],
  ['SMF', 'Sacramento'],
  ['RNO', 'Reno'],
  ['BOI', 'Boise'],
  ['PDX', 'Portland'],
  ['SEA', 'Seattle'],
  ['ANC', 'Anchorage'],
  ['HNL', 'Honolulu'],
  ['OGG', 'Maui'],
  // Canadá
  ['YYZ', 'Toronto'],
  ['YUL', 'Montreal'],
  ['YVR', 'Vancouver'],
  ['YYC', 'Calgary'],
  ['YEG', 'Edmonton'],
  ['YOW', 'Ottawa'],
  ['YQB', 'Quebec'],
  ['YWG', 'Winnipeg'],
  ['YHZ', 'Halifax'],
  ['YYJ', 'Victoria'],
  // España y Portugal
  ['MAD', 'Madrid'],
  ['BCN', 'Barcelona'],
  ['AGP', 'Málaga'],
  ['SVQ', 'Sevilla'],
  ['VLC', 'Valencia'],
  ['ALC', 'Alicante'],
  ['BIO', 'Bilbao'],
  ['SCQ', 'Santiago de Compostela'],
  ['PMI', 'Palma de Mallorca'],
  ['IBZ', 'Ibiza'],
  ['TFS', 'Tenerife (Sur)'],
  ['TFN', 'Tenerife (Norte)'],
  ['LPA', 'Las Palmas'],
  ['LIS', 'Lisboa'],
  ['OPO', 'Oporto'],
  ['FAO', 'Faro'],
  ['FNC', 'Madeira'],
  ['PDL', 'Azores (Ponta Delgada)'],
  // Resto de Europa
  ['CDG', 'París (Charles de Gaulle)'],
  ['ORY', 'París (Orly)'],
  ['NCE', 'Niza'],
  ['LYS', 'Lyon'],
  ['MRS', 'Marsella'],
  ['TLS', 'Toulouse'],
  ['BOD', 'Burdeos'],
  ['NTE', 'Nantes'],
  ['FCO', 'Roma (Fiumicino)'],
  ['CIA', 'Roma (Ciampino)'],
  ['MXP', 'Milán (Malpensa)'],
  ['LIN', 'Milán (Linate)'],
  ['BGY', 'Bérgamo'],
  ['VCE', 'Venecia'],
  ['VRN', 'Verona'],
  ['TRN', 'Turín'],
  ['BLQ', 'Bolonia'],
  ['FLR', 'Florencia'],
  ['PSA', 'Pisa'],
  ['NAP', 'Nápoles'],
  ['BRI', 'Bari'],
  ['CTA', 'Catania'],
  ['PMO', 'Palermo'],
  ['CAG', 'Cagliari'],
  ['OLB', 'Olbia'],
  ['LHR', 'Londres (Heathrow)'],
  ['LGW', 'Londres (Gatwick)'],
  ['STN', 'Londres (Stansted)'],
  ['LTN', 'Londres (Luton)'],
  ['LCY', 'Londres (City)'],
  ['MAN', 'Mánchester'],
  ['BHX', 'Birmingham'],
  ['BRS', 'Bristol'],
  ['LPL', 'Liverpool'],
  ['NCL', 'Newcastle'],
  ['EDI', 'Edimburgo'],
  ['GLA', 'Glasgow'],
  ['BFS', 'Belfast'],
  ['DUB', 'Dublín'],
  ['ORK', 'Cork'],
  ['SNN', 'Shannon'],
  ['FRA', 'Fráncfort'],
  ['MUC', 'Múnich'],
  ['BER', 'Berlín'],
  ['DUS', 'Düsseldorf'],
  ['HAM', 'Hamburgo'],
  ['CGN', 'Colonia'],
  ['STR', 'Stuttgart'],
  ['HAJ', 'Hannover'],
  ['NUE', 'Núremberg'],
  ['AMS', 'Ámsterdam'],
  ['EIN', 'Eindhoven'],
  ['RTM', 'Róterdam'],
  ['BRU', 'Bruselas'],
  ['CRL', 'Charleroi'],
  ['ZRH', 'Zúrich'],
  ['GVA', 'Ginebra'],
  ['BSL', 'Basilea'],
  ['VIE', 'Viena'],
  ['SZG', 'Salzburgo'],
  ['INN', 'Innsbruck'],
  ['CPH', 'Copenhague'],
  ['ARN', 'Estocolmo'],
  ['GOT', 'Gotemburgo'],
  ['OSL', 'Oslo'],
  ['BGO', 'Bergen'],
  ['TOS', 'Tromsø'],
  ['HEL', 'Helsinki'],
  ['KEF', 'Reikiavik'],
  ['PRG', 'Praga'],
  ['BUD', 'Budapest'],
  ['WAW', 'Varsovia'],
  ['KRK', 'Cracovia'],
  ['GDN', 'Gdansk'],
  ['OTP', 'Bucarest'],
  ['SOF', 'Sofía'],
  ['BEG', 'Belgrado'],
  ['ZAG', 'Zagreb'],
  ['SPU', 'Split'],
  ['DBV', 'Dubrovnik'],
  ['LJU', 'Liubliana'],
  ['TIA', 'Tirana'],
  ['RIX', 'Riga'],
  ['TLL', 'Tallin'],
  ['VNO', 'Vilna'],
  ['ATH', 'Atenas'],
  ['SKG', 'Salónica'],
  ['HER', 'Heraclión'],
  ['CHQ', 'La Canea'],
  ['RHO', 'Rodas'],
  ['CFU', 'Corfú'],
  ['JTR', 'Santorini'],
  ['JMK', 'Míconos'],
  ['MLA', 'Malta'],
  ['LCA', 'Lárnaca'],
  ['IST', 'Estambul'],
  ['SAW', 'Estambul (Sabiha Gökçen)'],
  ['ESB', 'Ankara'],
  ['ADB', 'Esmirna'],
  ['AYT', 'Antalya'],
  // Medio Oriente y África
  ['DXB', 'Dubái'],
  ['AUH', 'Abu Dabi'],
  ['DOH', 'Doha'],
  ['RUH', 'Riad'],
  ['JED', 'Yeda'],
  ['AMM', 'Amán'],
  ['TLV', 'Tel Aviv'],
  ['BEY', 'Beirut'],
  ['CAI', 'El Cairo'],
  ['HRG', 'Hurgada'],
  ['SSH', 'Sharm el Sheij'],
  ['RAK', 'Marrakech'],
  ['CMN', 'Casablanca'],
  ['FEZ', 'Fez'],
  ['TUN', 'Túnez'],
  ['ALG', 'Argel'],
  ['JNB', 'Johannesburgo'],
  ['CPT', 'Ciudad del Cabo'],
  ['DUR', 'Durban'],
  ['NBO', 'Nairobi'],
  ['JRO', 'Kilimanjaro'],
  ['ZNZ', 'Zanzíbar'],
  ['ADD', 'Adís Abeba'],
  ['LOS', 'Lagos'],
  ['ACC', 'Acra'],
  ['DKR', 'Dakar'],
  ['MRU', 'Mauricio'],
  ['SEZ', 'Seychelles'],
  // Asia
  ['NRT', 'Tokio (Narita)'],
  ['HND', 'Tokio (Haneda)'],
  ['KIX', 'Osaka'],
  ['NGO', 'Nagoya'],
  ['CTS', 'Sapporo'],
  ['FUK', 'Fukuoka'],
  ['OKA', 'Okinawa'],
  ['ICN', 'Seúl'],
  ['PEK', 'Pekín (Capital)'],
  ['PKX', 'Pekín (Daxing)'],
  ['PVG', 'Shanghái'],
  ['CAN', 'Cantón'],
  ['SZX', 'Shenzhen'],
  ['CTU', 'Chengdú'],
  ['XIY', 'Xi’an'],
  ['HKG', 'Hong Kong'],
  ['MFM', 'Macao'],
  ['TPE', 'Taipéi'],
  ['BKK', 'Bangkok (Suvarnabhumi)'],
  ['DMK', 'Bangkok (Don Mueang)'],
  ['HKT', 'Phuket'],
  ['CNX', 'Chiang Mai'],
  ['KBV', 'Krabi'],
  ['USM', 'Koh Samui'],
  ['SIN', 'Singapur'],
  ['KUL', 'Kuala Lumpur'],
  ['PEN', 'Penang'],
  ['LGK', 'Langkawi'],
  ['CGK', 'Yakarta'],
  ['DPS', 'Bali'],
  ['SUB', 'Surabaya'],
  ['MNL', 'Manila'],
  ['CEB', 'Cebú'],
  ['HAN', 'Hanói'],
  ['SGN', 'Ciudad Ho Chi Minh'],
  ['DAD', 'Da Nang'],
  ['PNH', 'Nom Pen'],
  ['REP', 'Siem Riep'],
  ['RGN', 'Rangún'],
  ['DEL', 'Delhi'],
  ['BOM', 'Bombay'],
  ['BLR', 'Bangalore'],
  ['MAA', 'Chennai'],
  ['HYD', 'Hyderabad'],
  ['CCU', 'Calcuta'],
  ['COK', 'Kochi'],
  ['GOI', 'Goa'],
  ['JAI', 'Jaipur'],
  ['CMB', 'Colombo'],
  ['MLE', 'Maldivas'],
  ['KTM', 'Katmandú'],
  ['DAC', 'Daca'],
  ['ISB', 'Islamabad'],
  ['KHI', 'Karachi'],
  ['LHE', 'Lahore'],
  ['TAS', 'Taskent'],
  ['ALA', 'Almaty'],
  ['GYD', 'Bakú'],
  ['TBS', 'Tiflis'],
  ['EVN', 'Ereván'],
  // Oceanía
  ['SYD', 'Sídney'],
  ['MEL', 'Melbourne'],
  ['BNE', 'Brisbane'],
  ['PER', 'Perth'],
  ['ADL', 'Adelaida'],
  ['OOL', 'Gold Coast'],
  ['CNS', 'Cairns'],
  ['HBA', 'Hobart'],
  ['DRW', 'Darwin'],
  ['AKL', 'Auckland'],
  ['WLG', 'Wellington'],
  ['CHC', 'Christchurch'],
  ['ZQN', 'Queenstown'],
  ['NAN', 'Nadi'],
  ['PPT', 'Papeete'],
  ['NOU', 'Numea'],
  ['GUM', 'Guam'],
];

/** The one datalist both airports of a pasaje read from: only one pasaje is
 *  ever on screen, and the options are hundreds of nodes. */
export const AIRPORT_LIST_ID = 'viajes-aeropuertos';

/** How long an IATA code is, and so how much of an option's value is one. */
const IATA_LENGTH = 3;

/** The city each listed code stands for. */
const CITIES = new Map(AIRPORTS.map(([code, city]) => [code, city]));

/**
 * How an airport is offered: the code first, then the city, in one string.
 * Both halves are in the *value* because that is the only part Firefox matches
 * a datalist option by — a `label` never takes part in the filtering there — and
 * the code leads it so a narrow field still shows the half that is being looked
 * for.
 */
export function airportOptionValue(code: string, city: string): string {
  return city ? `${code} — ${city}` : code;
}

/**
 * The code behind whatever is in the field: an option picked from the list, a
 * code typed straight in, or a city named well enough to mean one airport and
 * no other. Null while it means nothing yet — the field holds codes, so text
 * that names no airport is never turned into three letters that mean another.
 */
export function resolveAirportCode(text: string): string | null {
  const typed = text.trim();
  const head = typed.slice(0, IATA_LENGTH).toUpperCase();
  const isCode = /^[A-Z]{3}$/.test(head);
  const alone = typed.length === IATA_LENGTH;

  // A picked option hands over its whole value, which the code leads.
  if (isCode && !alone && typed[IATA_LENGTH] === ' ') return head;
  // Three letters that name an airport are that airport, whatever city they
  // also happen to begin.
  if (isCode && alone && CITIES.has(head)) return head;

  const needle = normalize(typed);
  const named = typed
    ? AIRPORTS.filter(([code, city]) => normalize(`${code} ${city}`).includes(needle))
    : [];
  if (named.length === 1) return named[0][0];

  // Three letters the list has never heard of are still a code: no list of a
  // few hundred can be complete, and where the household flies is its own.
  return isCode && alone ? head : null;
}

/**
 * The codes to offer, the household's own first: every airport already used in
 * a pasaje, most used first, then the bundled list. Where the household flies
 * is private, so that half is read from the device's own rows and never
 * committed.
 */
export function airportOptions(items: readonly TripItem[]): (readonly [string, string])[] {
  const used = new Map<string, number>();
  for (const item of items) {
    for (const code of [item.from_code, item.to_code]) {
      if (code) used.set(code, (used.get(code) ?? 0) + 1);
    }
  }
  const own = [...used.entries()]
    .sort(([codeA, timesA], [codeB, timesB]) => timesB - timesA || codeA.localeCompare(codeB))
    .map(([code]): readonly [string, string] => [code, CITIES.get(code) ?? '']);
  return [...own, ...AIRPORTS.filter(([code]) => !used.has(code))];
}
